name: build & test
on:
  push:
    branches: [ 'develop', 'feature/**', 'bugfix/**' ]
  pull_request:
    branches: [ 'develop', 'feature/**', 'bugfix/**' ]
concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B verify --no-transfer-progress
