name: Generate Changelog
on:
  workflow_run:
    workflows: ["Create Release Anchor", "Increment Version on Commit"]
    types: [completed]
    branches: [ 'release/**', 'hotfix/**' ]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine trigger context
        id: context
        shell: bash
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
          
          if [[ "$WORKFLOW_NAME" == "Create Release Anchor" ]]; then
            echo "trigger=branch_creation" >> "$GITHUB_OUTPUT"
            echo "📅 Changelog triggered by: Branch creation"
          else
            echo "trigger=version_increment" >> "$GITHUB_OUTPUT"
            echo "📅 Changelog triggered by: Version increment"
          fi

      - name: Wait for anchor tag availability
        shell: bash
        run: |
          BRANCH="${{ steps.context.outputs.branch }}"
          VERSION="${BRANCH#*/}"
          KIND="${BRANCH%%/*}"
          BASE_TAG="$KIND-base/$VERSION"
          
          echo "⏳ Ensuring anchor tag $BASE_TAG is available..."
          
          for i in {1..30}; do
            git fetch --tags --quiet
            if git rev-parse "$BASE_TAG" >/dev/null 2>&1; then
              echo "✅ Anchor tag $BASE_TAG confirmed!"
              break
            else
              echo "⏱️ Attempt $i/30: Waiting for anchor tag..."
              sleep 2
            fi
          done
          
          if ! git rev-parse "$BASE_TAG" >/dev/null 2>&1; then
            echo "❌ Anchor tag $BASE_TAG not found after waiting"
            exit 1
          fi

      - name: Generate CHANGELOG
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: angular
          tag-prefix: ${{ steps.context.outputs.branch }}_base/  # Usar branch específica como prefix
          output-file: CHANGELOG.md
          skip-bump: 'true'
          skip-tag: 'true'
          skip-version-file: 'true'
          release-count: '0'

      - name: Commit changelog
        shell: bash
        run: |
          BRANCH="${{ steps.context.outputs.branch }}"
          TRIGGER="${{ steps.context.outputs.trigger }}"
          
          git add CHANGELOG.md
          
          if git diff --cached --quiet; then
            echo "ℹ️ No changes in CHANGELOG.md"
            exit 0
          fi
          
          if [[ "$TRIGGER" == "branch_creation" ]]; then
            COMMIT_MSG="docs(changelog): initial changelog for ${BRANCH}"
          else
            COMMIT_MSG="docs(changelog): update for ${BRANCH} [skip ci]"
          fi
          
          git commit -m "$COMMIT_MSG"
          git push origin HEAD:"$BRANCH"
          
          echo "✅ CHANGELOG updated successfully"
