name: java-anchor
on:
  create:
    branches: ['release/*','hotfix/*']
permissions: { contents: write }

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  anchor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '24' }

      - name: Bump version + tag âncora
        shell: bash
        run: |
          set -euo pipefail
          BR=${GITHUB_REF_NAME}              # release/1.3.0
          VER=${BR#*/}                       # 1.3.0
          KIND=${BR%%/*}                     # release
          mvn -q versions:set -DnewVersion="$VER" -DprocessAllModules=true -DgenerateBackupPoms=false
          mvn -q versions:commit
          npx --yes conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: init $VER & changelog"
          git tag -a "$KIND-base/$VER" -m "anchor $VER"
          git push origin HEAD:"$BR"
          git push origin "$KIND-base/$VER"
