name: java-anchor
on:
  create:
    branches: [ 'release/*','hotfix/*' ]
permissions: { contents: write }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  anchor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '24' }
      - name: Bump version from branch and tag anchor
        shell: bash
        run: |
          set -euo pipefail
          BR="${GITHUB_REF_NAME}"      # release/1.3.0 ou hotfix/1.3.0
          VER="${BR#*/}"               # 1.3.0
          KIND="${BR%%/*}"             # release|hotfix
          mvn -q versions:set -DnewVersion="$VER" -DprocessAllModules=true -DgenerateBackupPoms=false
          mvn -q versions:commit
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: set version $VER from $BR" || true
          git tag -a "$KIND-base/$VER" -m "base of $BR at creation"
          git push origin HEAD:"$BR"
          git push origin "$KIND-base/$VER"
