name: java-anchor

on:
  create:
    branches: ['release/*', 'hotfix/*']

permissions:
  contents: write          # para commitar versão + changelog

# Impede concorrência entre fluxos da mesma branch
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  anchor:
    runs-on: ubuntu-latest
    steps:
      # 1) checkout com histórico completo
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 2) tool-chain Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      # 3) tool-chain Node (para conventional-changelog)
      - uses: actions/setup-node@v4              # ← novo
        with: { node-version: '22' }

      # 4) CLI + preset angular
      - name: Install changelog CLI
        run: npm install -g conventional-changelog-cli@2 conventional-changelog-angular@6

      # 5) bump versão, gerar CHANGELOG, criar tag âncora
      - name: Bump version, generate changelog, tag anchor
        shell: bash
        run: |
          set -euo pipefail

          BR="${GITHUB_REF_NAME}"            # release/1.3.0  ou hotfix/1.3.0
          VER="${BR#*/}"                     # 1.3.0
          KIND="${BR%%/*}"                   # release | hotfix

          # bump pom.xml -> X.Y.0
          mvn -q versions:set -DnewVersion="$VER" \
               -DprocessAllModules=true -DgenerateBackupPoms=false
          mvn -q versions:commit

          # gera CHANGELOG do anchor range (ainda inexistente ⇒ todo histórico)
          conventional-changelog \
            -p angular \
            -i CHANGELOG.md -s -r 0 \
            --tag-prefix "${KIND}-base/"

          # commit versão + changelog e criar tag âncora
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: init $VER & changelog"
          git tag -a "$KIND-base/$VER" -m "anchor $VER"
          git push origin HEAD:"$BR"
          git push origin "$KIND-base/$VER"
