name: master-release
on:
  push:
    branches: [ 'master' ]

permissions:
  contents: write
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository_owner }}/semantic-versioning-poc

jobs:
  cut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: npm i -g conventional-changelog-cli@2 conventional-changelog-angular@6

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - id: ver
        run: |
          V=$(mvn -q -DforceStdout -Dexpression=project.version -DnonRecursive=true help:evaluate)
          echo "version=$V" >>"$GITHUB_OUTPUT"

      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag -a "v${{ steps.ver.outputs.version }}" -m "release ${{ steps.ver.outputs.version }}"
          
          npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0

          git add CHANGELOG.md
          git commit -m "docs(changelog): ${{ steps.ver.outputs.version }} [skip ci]" || true
          
          git tag -f -a "v${{ steps.ver.outputs.version }}" -m "release ${{ steps.ver.outputs.version }}"
          
          git push origin HEAD
          git push -f origin "v${{ steps.ver.outputs.version }}"

      - run: mvn -B -DskipTests package

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.ver.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
