name: Publish Docker Image
on:
  push:
    branches: [ 'develop', main ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/semantic-versioning-poc

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build JAR
        run: mvn -B -DskipTests package

      - name: Compute docker tag
        id: vars
        shell: bash
        run: |
          CURRENT_BRANCH="${GITHUB_REF_NAME}"
          if [[ "$CURRENT_BRANCH" == "develop" ]]; then
            TAG="develop-${GITHUB_RUN_NUMBER}"
          elif [[ "$CURRENT_BRANCH" == "main" ]]; then
            TAG="latest"
          else
            TAG="${CURRENT_BRANCH//\//-}-${GITHUB_SHA::7}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.vars.outputs.tag }}
